# IMPORTANT: DO NOT RENAME THIS FILE
# It uses Trusted Publisher to deploy without token
# https://www.npmjs.com/package/chunkdown/access

name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  id-token: write # needed for npm publish with provenance

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      # http://github.com/actions/checkout
      - uses: actions/checkout@v5
      # https://github.com/pnpm/action-setup
      - uses: pnpm/action-setup@v4
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test
      - run: pnpm publish --provenance --no-git-checks
